name: CD

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get version
        uses: dotnet/nbgv@master
        id: nbgv

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Publish
        run: dotnet publish HuettenZeiten.Cli/HuettenZeiten.Cli.csproj -c Release -r win-x64 --self-contained -o publish

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.nbgv.outputs.SemVer2 }}
          files: publish/HuettenZeiten.Cli.exe
