name: CD

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  build-and-release:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Publish
        run: dotnet publish HuettenZeiten.Cli/HuettenZeiten.Cli.csproj -c Release -r win-x64 --self-contained -o publish

      - name: Create GitHub Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: publish/HuettenZeiten.Cli.exe
